language: ruby
env:
  - JRUBY_OPTS=-J-Xmx1g
jdk:
  - oraclejdk7
  - openjdk7
rvm:
  - jruby
before_script:
  - bundle exec cap local externals:setup
  - touch config/environments/test_secret.rb
  - bundle exec rake git:db:canonical:clone
  - bundle exec rake db:migrate
