language: ruby
cache: bundler
sudo: false
env:
  global:
    - JRUBY_OPTS="-J-Xmx1g --2.0"
jobs:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: trusty
      jdk: openjdk9
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: linux
      dist: trusty
      jdk: oraclejdk11
    - os: linux
      dist: xenial
      jdk: openjdk8
    - os: linux
      dist: xenial
      jdk: openjdk9
    - os: linux
      dist: xenial
      jdk: openjdk10
    - os: linux
      dist: xenial
      jdk: openjdk11
    - os: linux
      dist: bionic
      jdk: openjdk8
    - os: linux
      dist: bionic
      jdk: openjdk9
    - os: linux
      dist: bionic
      jdk: openjdk10
    - os: linux
      dist: bionic
      jdk: openjdk11
rvm:
  - jruby-9.1.17.0
before_install:
  - gem install bundler --version '<2.0'
before_script:
  - gem --version
  - bundle exec cap local externals:setup
  - touch config/environments/test_secret.rb
  - bundle exec rake git:db:canonical:clone
  - bundle exec rake db:migrate
after_failure:
  - curl --upload-file log/test.log https://transfer.sh/test.log | cat && echo
