dist:
  - trusty
  - precise
language: ruby
sudo: false
env:
  - JRUBY_OPTS="-J-Xmx1g --2.0"
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
rvm:
  - jruby-1.7.26
matrix:
  exclude:
    - dist: trusty
      jdk: oraclejdk7
    - dist: precise
      jdk: oraclejdk8
    - dist: precise
      jdk: openjdk7
before_install:
  - command -v bundle >/dev/null 2>&1 || gem install bundler
before_script:
  - gem pristine executable-hooks
  - gem pristine gem-wrappers
  - gem pristine jruby-launcher
  - gem --version
  - bundle exec cap local externals:setup
  - touch config/environments/test_secret.rb
  - bundle exec rake git:db:canonical:clone
  - bundle exec rake db:migrate
